### ISSUE TITLE
Doesn't seem to work with your Nova Button package

### ISSUE THREAD

**Issue by FrittenKeeZ** [dillingham/nova-grouped-field#4]
Buttons don't appear in the group.

**Comment by timcv** [comment]
Same here.

**Comment by LorenzoSapora** [comment]
I managed to get it to display by adding `->showLabels()` but the buttons aren't actionable. Is there something we're missing, @dillingham ?

Here's a mock version of what I have:

```php
            Grouped::make('Rank')->fields([
                Button::make('1')->style('grey-outline'),
                Button::make('2')->style('grey-outline'),
                Button::make('3')->style('grey-outline'),
                Button::make('4')->style('grey-outline'),
                Button::make('5')->style('grey-outline'),
            ])->showLabels()->separator(''),
```

And it outputs on index: 

![image](https://user-images.githubusercontent.com/25519274/72212737-9e80a500-34d9-11ea-8345-b7baee569863.png)

Ignore that none of the buttons have events/actions attached, was just trying this package out.

I assume this is because it's stripping out the labels, maybe? I'm hitting a wall.

**Comment by dillingham** [comment]
@LorenzoSapora Ill take a look

**Comment by dillingham** [comment]
@LorenzoSapora after adding a check if `nova-button` it for some reason didn't output the component. Still investigating.

**Comment by LorenzoSapora** [comment]
@dillingham anything I can help with? Where's the issue? How far did you get?

**Comment by LorenzoSapora** [comment]
Whoa, time flies when you're having covid fun. It feels like I posted the above a month or two ago.. If you remember what the issue was with this, I'd like to help look into it
